// <auto-generated />
using System;
using EmojiMapNet9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmojiMapNet9.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203213105_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmojiMapNet9.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MarkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MarkerId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-77777777777d"),
                            Content = "Ale super miejsce! Muszę tam pojechać.",
                            CreatedAt = new DateTime(2025, 12, 1, 5, 37, 0, 0, DateTimeKind.Utc),
                            MarkerId = new Guid("55555555-5555-5555-5555-55555555555c"),
                            UserId = new Guid("11111111-1111-1111-1111-11111111111a")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-88888888888d"),
                            Content = "Potwierdzam, pizza rewelacja!",
                            CreatedAt = new DateTime(2025, 12, 2, 11, 34, 0, 0, DateTimeKind.Utc),
                            MarkerId = new Guid("66666666-6666-6666-6666-66666666666c"),
                            UserId = new Guid("22222222-2222-2222-2222-22222222222a")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-99999999999d"),
                            Content = "Świetny sprzęt!",
                            CreatedAt = new DateTime(2025, 12, 1, 7, 37, 0, 0, DateTimeKind.Utc),
                            MarkerId = new Guid("77777777-7777-7777-7777-77777777777c"),
                            UserId = new Guid("22222222-2222-2222-2222-22222222222a")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Content = "Bardzo ciekawe.",
                            CreatedAt = new DateTime(2025, 12, 2, 3, 30, 0, 0, DateTimeKind.Utc),
                            MarkerId = new Guid("88888888-8888-8888-8888-88888888888c"),
                            UserId = new Guid("33333333-3333-3333-3333-33333333333a")
                        });
                });

            modelBuilder.Entity("EmojiMapNet9.Entities.Marker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Markers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-55555555555c"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tutaj jest bardzo cicho.",
                            Emoji = "NATURE",
                            Latitude = 50.037503000000001,
                            Longitude = 19.910568999999999,
                            Title = "Zakrzówek",
                            UserId = new Guid("22222222-2222-2222-2222-22222222222a"),
                            Username = "Test",
                            Visibility = "public"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-66666666666c"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Najlepsza pizza w mieście.",
                            Emoji = "FOOD",
                            Latitude = 50.010688000000002,
                            Longitude = 19.956641000000001,
                            Title = "Dobra Pizza",
                            UserId = new Guid("11111111-1111-1111-1111-11111111111a"),
                            Username = "Admin",
                            Visibility = "public"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-77777777777c"),
                            CreatedAt = new DateTime(2025, 1, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dobre miejsce na trening.",
                            Emoji = "GYM",
                            Latitude = 50.068503999999997,
                            Longitude = 19.900952,
                            Title = "Basen AGH",
                            UserId = new Guid("33333333-3333-3333-3333-33333333333a"),
                            Username = "Test2",
                            Visibility = "public"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-88888888888c"),
                            CreatedAt = new DateTime(2025, 1, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wystawa fajna.",
                            Emoji = "MUSEUM",
                            Latitude = 50.060299000000001,
                            Longitude = 19.923598999999999,
                            Title = "Muzeum Narodowe",
                            UserId = new Guid("11111111-1111-1111-1111-11111111111a"),
                            Username = "Admin",
                            Visibility = "public"
                        });
                });

            modelBuilder.Entity("EmojiMapNet9.Entities.MarkerTag", b =>
                {
                    b.Property<Guid>("MarkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MarkerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MarkerTags", t =>
                        {
                            t.HasTrigger("CleanupUnusedTags");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            MarkerId = new Guid("55555555-5555-5555-5555-55555555555c"),
                            TagId = new Guid("33333333-3333-3333-3333-33333333333b")
                        },
                        new
                        {
                            MarkerId = new Guid("66666666-6666-6666-6666-66666666666c"),
                            TagId = new Guid("44444444-4444-4444-4444-44444444444b")
                        },
                        new
                        {
                            MarkerId = new Guid("77777777-7777-7777-7777-77777777777c"),
                            TagId = new Guid("55555555-5555-5555-5555-55555555555b")
                        },
                        new
                        {
                            MarkerId = new Guid("88888888-8888-8888-8888-88888888888c"),
                            TagId = new Guid("66666666-6666-6666-6666-66666666666b")
                        });
                });

            modelBuilder.Entity("EmojiMapNet9.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-33333333333b"),
                            ColorTag = "#2ecc71",
                            Title = "Natura",
                            UserId = new Guid("11111111-1111-1111-1111-11111111111a"),
                            Visibility = "public"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-44444444444b"),
                            ColorTag = "#e74c3c",
                            Title = "Jedzenie",
                            UserId = new Guid("22222222-2222-2222-2222-22222222222a"),
                            Visibility = "public"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-55555555555b"),
                            ColorTag = "#3498db",
                            Title = "Sport",
                            UserId = new Guid("33333333-3333-3333-3333-33333333333a"),
                            Visibility = "public"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-66666666666b"),
                            ColorTag = "#9b59b6",
                            Title = "Kultura",
                            UserId = new Guid("11111111-1111-1111-1111-11111111111a"),
                            Visibility = "public"
                        });
                });

            modelBuilder.Entity("EmojiMapNet9.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111a"),
                            Email = "admin@admin.com",
                            PasswordHash = "",
                            Role = "admin",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-22222222222a"),
                            Email = "test@test.com",
                            PasswordHash = "",
                            Role = "user",
                            Username = "Test"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-33333333333a"),
                            Email = "test2@test.com",
                            PasswordHash = "",
                            Role = "user",
                            Username = "Test2"
                        });
                });

            modelBuilder.Entity("EmojiMapNet9.Entities.Comment", b =>
                {
                    b.HasOne("EmojiMapNet9.Entities.Marker", "Marker")
                        .WithMany()
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmojiMapNet9.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmojiMapNet9.Entities.Marker", b =>
                {
                    b.HasOne("EmojiMapNet9.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmojiMapNet9.Entities.MarkerTag", b =>
                {
                    b.HasOne("EmojiMapNet9.Entities.Marker", null)
                        .WithMany()
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmojiMapNet9.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmojiMapNet9.Entities.Tag", b =>
                {
                    b.HasOne("EmojiMapNet9.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
